### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by licketylips** [LiveSparks/Notification-Flag#1]
I like your Flag notifier code, are you able to modify the code to light up an Led instead then self reset after 5 minutes ?

**Comment by LiveSparks** [comment]
Inside the loop, replace
`Serial.println("Flag On!");
      mailFlag.write(90);
      sendDweet();`

with

`Serial.println("Flag ON");
digitalWrite(LED,HIGH);
sendDweet();
delay(5*60*1000);
Serial.println("Flag Reset");
digitalWrite(LED,LOW);`
